name: flutter_nevis_cli
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/commands.json

  fonts:
    - family: VazirMatnBlack
      fonts:
        - asset: fonts/VazirMatnBlack.ttf
    - family: VazirMatnRegular
      fonts:
        - asset: fonts/VazirMatnRegular.ttf